# Generated by Django 2.0.2 on 2018-02-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Title',
        ),
    ]
