# Generated by Django 2.0.2 on 2018-02-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontocert',
            name='Start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
