# Generated by Django 2.0.3 on 2018-03-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0002_auto_20180307_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontocompany',
            name='Desc',
            field=models.CharField(default='None', max_length=3000, verbose_name='Company Description'),
        ),
    ]
