# Generated by Django 2.0.2 on 2018-02-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0002_remove_person_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontocert',
            name='Completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completion Date'),
        ),
    ]
