# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0002_remove_persontoschool_courseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ZipCode',
            field=models.IntegerField(default='0', verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='EndDate',
            field=models.DateField(default=14, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='StartDate',
            field=models.DateField(default=14, verbose_name='Start Date'),
        ),
    ]
