# Generated by Django 2.0.2 on 2018-02-23 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0002_auto_20180222_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='CreatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.Document'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='ExperienceOnJob',
            field=models.CharField(default='None', max_length=1000, verbose_name='Experience on Job'),
        ),
        migrations.AlterField(
            model_name='persontotraining',
            name='Start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='school',
            name='Name',
            field=models.CharField(default='None', max_length=150, verbose_name='School'),
        ),
    ]
