# Generated by Django 2.0.2 on 2018-02-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0003_auto_20180214_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontotraining',
            name='Completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completion Date'),
        ),
    ]
