# Generated by Django 2.0.3 on 2018-03-08 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0003_auto_20180307_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonToTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PersonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.Person')),
                ('TitleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.Title')),
            ],
        ),
    ]
