# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0004_auto_20170821_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontocompany',
            name='EndDate',
            field=models.DateField(default=23, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='StartDate',
            field=models.DateField(default=23, verbose_name='Start Date'),
        ),
    ]
