# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0005_auto_20170823_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontocompany',
            name='EndDate',
            field=models.DateField(default=24, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='StartDate',
            field=models.DateField(default=24, verbose_name='Start Date'),
        ),
    ]
