# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0006_auto_20170824_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='document',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='person',
            name='Address',
            field=models.CharField(blank=True, default='Not Parsed', max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Email',
            field=models.CharField(blank=True, default='Not Parsed', max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='GitHub',
            field=models.CharField(blank=True, default='Not Parsed', max_length=70, null=True, verbose_name='GitHub'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Linkedin',
            field=models.CharField(blank=True, default='Not Parsed', max_length=70, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='person',
            name='PhoneNumber',
            field=models.CharField(blank=True, default='Not Parsed', max_length=50, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='State',
            field=models.CharField(blank=True, default='Not Parsed', max_length=25, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ZipCode',
            field=models.IntegerField(blank=True, default=0, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='EndDate',
            field=models.DateField(null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='StartDate',
            field=models.DateField(null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='persontoskills',
            name='YearsOfExperience',
            field=models.CharField(default=1, max_length=3, verbose_name='Years Of Experience'),
        ),
    ]
