# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0007_auto_20171115_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='CreationDate',
            field=models.DateField(auto_now=True, verbose_name='Created On'),
        ),
    ]
