# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0007_auto_20171127_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontocompany',
            name='EndDate',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='persontocompany',
            name='StartDate',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
