# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0008_auto_20171127_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='persontoskills',
            name='Level',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=50, verbose_name='Level'),
        ),
    ]
