# Generated by Django 2.0.2 on 2018-02-07 20:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0011_auto_20180202_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='certifications',
            name='Completion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 7, 15, 29, 35, 120252), verbose_name='Completion Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certifications',
            name='Start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Start Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainings',
            name='Completion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 7, 15, 29, 50, 756917), verbose_name='Completion Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainings',
            name='Start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Start Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='Title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RSR.Title'),
        ),
    ]
