# Generated by Django 2.0.2 on 2018-02-08 01:26

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0012_auto_20180207_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certifications',
            name='Completion_date',
        ),
        migrations.RemoveField(
            model_name='certifications',
            name='Interest',
        ),
        migrations.RemoveField(
            model_name='certifications',
            name='Start_date',
        ),
        migrations.RemoveField(
            model_name='trainings',
            name='Completion_date',
        ),
        migrations.RemoveField(
            model_name='trainings',
            name='Interest',
        ),
        migrations.RemoveField(
            model_name='trainings',
            name='Start_date',
        ),
        migrations.AddField(
            model_name='persontocert',
            name='Completion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 7, 20, 26, 8, 540799), verbose_name='Completion Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persontocert',
            name='Interest',
            field=models.CharField(choices=[('Interested', 'Interested'), ('In Progess', 'In Progess'), ('Completed', 'Completed')], default='Interested', max_length=50, verbose_name='Interest'),
        ),
        migrations.AddField(
            model_name='persontocert',
            name='Start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Start Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persontotraining',
            name='Completion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 7, 20, 26, 19, 387609), verbose_name='Completion Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persontotraining',
            name='Interest',
            field=models.CharField(choices=[('Interested', 'Interested'), ('In Progess', 'In Progess'), ('Completed', 'Completed')], default='Interested', max_length=50, verbose_name='Interest'),
        ),
        migrations.AddField(
            model_name='persontotraining',
            name='Start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Start Date'),
            preserve_default=False,
        ),
    ]
