# Generated by Django 2.0.2 on 2018-02-21 23:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField(default=None, max_length=50, verbose_name='First Name')),
                ('LName', models.CharField(default=None, max_length=50, verbose_name='Last Name')),
                ('username', models.CharField(default=None, max_length=50, verbose_name='Username')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=50, verbose_name='User')),
                ('date', models.DateField(blank=True, default=datetime.date.today, verbose_name='Date')),
                ('time_in', models.TimeField(blank=True, default=datetime.time(18, 41, 6, 892448), verbose_name='Time In')),
                ('time_out', models.TimeField(blank=True, default=datetime.time(18, 41, 6, 892478), verbose_name='Time Out')),
                ('active_session', models.BooleanField(default=True, verbose_name='Active Session')),
                ('summary', models.CharField(default='N/A', max_length=5000, verbose_name='Summary')),
                ('duration', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Duration')),
                ('intern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clockin.Intern')),
            ],
        ),
    ]
