# Generated by Django 2.0.2 on 2018-03-01 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0004_auto_20180301_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.time(16, 0, 19, 894926), verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_out',
            field=models.TimeField(blank=True, default=datetime.time(16, 0, 19, 894957), verbose_name='Time Out'),
        ),
    ]
