# Generated by Django 2.0.2 on 2018-03-01 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0005_auto_20180301_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.time(16, 17, 5, 20403), verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_out',
            field=models.TimeField(blank=True, default=datetime.time(16, 17, 5, 20444), verbose_name='Time Out'),
        ),
    ]
