# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 19:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0038_auto_20171202_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.time(14, 51, 39, 549098), verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_out',
            field=models.TimeField(blank=True, default=datetime.time(14, 51, 39, 549142), verbose_name='Time Out'),
        ),
    ]
