# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 20:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0039_auto_20171205_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.time(15, 11, 19, 419925), verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_out',
            field=models.TimeField(blank=True, default=datetime.time(15, 11, 19, 419964), verbose_name='Time Out'),
        ),
    ]
