# Generated by Django 2.0.2 on 2018-02-24 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180222_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='assigned_to',
            field=models.ManyToManyField(related_name='account_assigned_to', to='common.CRMUser'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_created_by', to='common.CRMUser'),
        ),
    ]
