# Generated by Django 2.0.2 on 2018-02-24 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20180222_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='crmuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='crmuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='crmuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='crmuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='comment',
            name='commented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.CRMUser'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(to='common.CRMUser'),
        ),
    ]
