# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 15:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ClockSequence',
            field=models.CharField(default=None, max_length=20, verbose_name='Clock Sequence'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ClockSequenceHistoric',
            field=models.CharField(default=None, max_length=50, verbose_name='ClockSequenceHistoric'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Comments',
            field=models.CharField(default=None, max_length=1000, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='employee',
            name='CommissionDueDate',
            field=models.DateField(default=datetime.date.today, verbose_name='Commission Due Date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='CommissionLogged',
            field=models.BooleanField(default=True, verbose_name='Commision Logged'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Created',
            field=models.DateField(default=datetime.date.today, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='employee',
            name='CreatedBy',
            field=models.CharField(default=None, max_length=20, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='employee',
            name='EffectiveDate',
            field=models.DateField(default=datetime.date.today, verbose_name='Effective Date of Change in Record'),
        ),
        migrations.AddField(
            model_name='employee',
            name='GbSecruityAccessRequest',
            field=models.CharField(default=None, max_length=50, verbose_name='Gb Security Access Request'),
        ),
        migrations.AddField(
            model_name='employee',
            name='OfferContractNDAFE',
            field=models.DateField(default=datetime.date.today, verbose_name='Offer Contract NDA FE'),
        ),
        migrations.AddField(
            model_name='employee',
            name='OfferContractSent',
            field=models.BooleanField(default=True, verbose_name='Offer Contract Sent'),
        ),
        migrations.AddField(
            model_name='employee',
            name='PayrollCompany',
            field=models.CharField(default=None, max_length=20, verbose_name='Payroll Company'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ProbationAlert',
            field=models.DateField(default=datetime.date.today, verbose_name='Probation Alert'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ProjectFunctionalTitle',
            field=models.CharField(default=None, max_length=50, verbose_name='Project Functional Title'),
        ),
        migrations.AddField(
            model_name='employee',
            name='RequestType',
            field=models.CharField(default=None, max_length=20, verbose_name='Request Type'),
        ),
        migrations.AddField(
            model_name='employee',
            name='SoftwareRequest',
            field=models.CharField(default=None, max_length=50, verbose_name='Software Request'),
        ),
        migrations.AddField(
            model_name='employee',
            name='SubmittedViaWebform',
            field=models.BooleanField(default=True, verbose_name='Submitted Via Webform (T/F)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ToolKit',
            field=models.BooleanField(default=True, verbose_name='Tool Kit'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='Comments',
            field=models.CharField(default=None, max_length=1000, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='ContractNumber',
            field=models.CharField(default=None, max_length=50, verbose_name='Contract Number'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='DocumentLocation',
            field=models.CharField(default=None, max_length=50, verbose_name='Document Location'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='IssuingCompany',
            field=models.CharField(default=None, max_length=50, verbose_name='Issuing Company'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='OrganizationType',
            field=models.CharField(default=None, max_length=50, verbose_name='Organization Type'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='POC',
            field=models.CharField(default=None, max_length=50, verbose_name='Point of Contact'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='Status',
            field=models.CharField(default=None, max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Address',
            field=models.CharField(default=None, max_length=50, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CAGE',
            field=models.CharField(default=None, max_length=50, verbose_name='CAGE'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='City',
            field=models.CharField(default=None, max_length=20, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Country',
            field=models.CharField(default=None, max_length=20, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='DBA',
            field=models.CharField(default=None, max_length=50, verbose_name='DBA'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='DUNs',
            field=models.CharField(default=None, max_length=9, verbose_name='DUNs'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Email',
            field=models.CharField(default=None, max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Fax',
            field=models.CharField(default=None, max_length=50, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='LegalName',
            field=models.CharField(default=None, max_length=50, verbose_name='Legal Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='POC',
            field=models.CharField(default=None, max_length=50, verbose_name='Point of Contact'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Phone',
            field=models.CharField(default=None, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='State',
            field=models.CharField(default=None, max_length=10, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='TIN',
            field=models.CharField(default=None, max_length=11, verbose_name='TIN'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ZipCode',
            field=models.CharField(default=None, max_length=10, verbose_name='Zip code'),
        ),
        migrations.AlterField(
            model_name='department',
            name='Fax',
            field=models.CharField(default=None, max_length=50, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='department',
            name='Location',
            field=models.CharField(default=None, max_length=50, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='department',
            name='Name',
            field=models.CharField(default=None, max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='Phone',
            field=models.CharField(default=None, max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='department',
            name='Supervisor',
            field=models.CharField(default=None, max_length=50, verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Addresses',
            field=models.CharField(default=None, max_length=30, verbose_name='Addresses'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='BusinessCard',
            field=models.CharField(default=None, max_length=50, verbose_name='Business Card'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='CAMPINSent',
            field=models.CharField(default=None, max_length=50, verbose_name='CAMPINSent'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='City',
            field=models.CharField(default=None, max_length=20, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ClearanceStatus',
            field=models.CharField(default=None, max_length=20, verbose_name='Clearance Status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ClearedType',
            field=models.CharField(default=None, max_length=20, verbose_name='Cleared Type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ClientBillRate',
            field=models.CharField(default=None, max_length=20, verbose_name='Client Bill Rate'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Computer',
            field=models.CharField(default=None, max_length=50, verbose_name='Computer'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ContractLaborCategory',
            field=models.CharField(default=None, max_length=20, verbose_name='Contract Labor Category'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Country',
            field=models.CharField(default=None, max_length=20, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Department',
            field=models.CharField(default=None, max_length=50, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmployementStatus',
            field=models.CharField(default=None, max_length=50, verbose_name='Employment Status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='FName',
            field=models.CharField(default=None, max_length=20, verbose_name='Resource Last Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='GSALaborCategory',
            field=models.CharField(default=None, max_length=20, verbose_name='GSA Labor Category'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='GSA_rate',
            field=models.CharField(default=None, max_length=50, verbose_name='GSA Rate'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='GSA_vehicle',
            field=models.CharField(default=None, max_length=50, verbose_name='GSA Vehicle'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=None, max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='LName',
            field=models.CharField(default=None, max_length=20, verbose_name='Resource First Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='MName',
            field=models.CharField(default=None, max_length=20, verbose_name='Resource First Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='PMICareerTitle',
            field=models.CharField(default=None, max_length=50, verbose_name='PMI Career Title    '),
        ),
        migrations.AlterField(
            model_name='employee',
            name='PMIEmail',
            field=models.CharField(default=None, max_length=50, verbose_name='PMI Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='PaycomLogin',
            field=models.CharField(default=None, max_length=50, verbose_name='Paycom Login'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='PersonalEmail',
            field=models.CharField(default=None, max_length=50, verbose_name='Personal Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Phone',
            field=models.CharField(default=None, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='RecruitmentSource',
            field=models.CharField(default=None, max_length=50, verbose_name='Recruitment Source'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ResourceType',
            field=models.CharField(default=None, max_length=20, verbose_name='Resource Type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ResponsibleRecruiter',
            field=models.CharField(default=None, max_length=50, verbose_name='Responsible Recruiter'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Salary',
            field=models.IntegerField(default=None, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='SalaryType',
            field=models.CharField(default=None, max_length=20, verbose_name='Salary Type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='SickLeaveHour',
            field=models.CharField(default=None, max_length=20, verbose_name='Sick Leave Hour'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='State',
            field=models.CharField(default=None, max_length=10, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='TypeOfContract',
            field=models.CharField(default=None, max_length=20, verbose_name='Type of Contract'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='VacationHour',
            field=models.CharField(default=None, max_length=20, verbose_name='Vacation Hour'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='WorkLocation',
            field=models.CharField(default=None, max_length=50, verbose_name='Work Location'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ZipCode',
            field=models.CharField(default=None, max_length=10, verbose_name='Zip code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eFAACT',
            field=models.CharField(default=None, max_length=50, verbose_name='eFAACT'),
        ),
        migrations.AlterField(
            model_name='googlegroup',
            name='Admin',
            field=models.CharField(default=None, max_length=50, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='googlegroup',
            name='Name',
            field=models.CharField(default=None, max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='Address',
            field=models.CharField(default=None, max_length=50, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='CAGE',
            field=models.CharField(default=None, max_length=50, verbose_name='CAGE'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='City',
            field=models.CharField(default=None, max_length=20, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='Country',
            field=models.CharField(default=None, max_length=20, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='DBA',
            field=models.CharField(default=None, max_length=50, verbose_name='DBA'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='DUNs',
            field=models.CharField(default=None, max_length=9, verbose_name='DUNs'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='Email',
            field=models.CharField(default=None, max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='Fax',
            field=models.CharField(default=None, max_length=50, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='LegalName',
            field=models.CharField(default=None, max_length=50, verbose_name='Legal Name'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='POC',
            field=models.CharField(default=None, max_length=50, verbose_name='Point of Contact'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='Phone',
            field=models.CharField(default=None, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='State',
            field=models.CharField(default=None, max_length=10, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='TIN',
            field=models.CharField(default=None, max_length=11, verbose_name='TIN'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='Type',
            field=models.CharField(default=None, max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='ZipCode',
            field=models.CharField(default=None, max_length=10, verbose_name='Zip code'),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='Address',
            field=models.CharField(default=None, max_length=50, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='CAGE',
            field=models.CharField(default=None, max_length=50, verbose_name='CAGE'),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='City',
            field=models.CharField(default=None, max_length=20, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='Country',
            field=models.CharField(default=None, max_length=20, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='DBA',
            field=models.CharField(default=None, max_length=50, verbose_name='DBA'),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='DUNs',
            field=models.CharField(default=None, max_length=50, verbose_name='DUNs'),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='Email',
            field=models.CharField(default=None, max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='Fax',
            field=models.CharField(default=None, max_length=50, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='LegalName',
            field=models.CharField(default=None, max_length=50, verbose_name='Legal Name'),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='POC',
            field=models.CharField(default=None, max_length=50, verbose_name='Point of Contact'),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='Phone',
            field=models.CharField(default=None, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='State',
            field=models.CharField(default=None, max_length=10, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='TIN',
            field=models.IntegerField(default=None, verbose_name='TIN'),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='ZipCode',
            field=models.CharField(default=None, max_length=10, verbose_name='Zip code'),
        ),
    ]
