# Generated by Django 2.0.2 on 2018-02-24 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oppurtunity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='assigned_to',
            field=models.ManyToManyField(related_name='opportunity_assigned_to', to='common.CRMUser'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='closed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.CRMUser'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_created_by', to='common.CRMUser'),
        ),
    ]
