# Generated by Django 2.0.2 on 2018-03-01 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('activity', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='assigned_to',
            field=models.ManyToManyField(related_name='activity_assigned_users', to='common.CRMUser'),
        ),
        migrations.AddField(
            model_name='activity',
            name='contacts',
            field=models.ManyToManyField(to='contacts.Contact'),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_created_by', to='common.CRMUser'),
        ),
    ]
