# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 18:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IssuingCompany', models.CharField(max_length=50, verbose_name='Issuing Company')),
                ('ContractNumber', models.CharField(max_length=50, verbose_name='Contract Number')),
                ('DocumentLocation', models.CharField(max_length=50, verbose_name='Document Location')),
                ('OrganizationType', models.CharField(max_length=50, verbose_name='Organization Type')),
                ('POC', models.CharField(max_length=50, verbose_name='Point of Contact')),
                ('EffectiveDate', models.DateField(default=datetime.date.today, verbose_name='Effective Date')),
                ('EndDate', models.DateField(default=datetime.date.today, verbose_name='End Date')),
                ('StartDate', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('Status', models.CharField(max_length=50, verbose_name='Status')),
                ('Comments', models.CharField(max_length=1000, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Contract_Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DBA', models.CharField(max_length=50, verbose_name='DBA')),
                ('Address', models.CharField(max_length=50, verbose_name='Address')),
                ('City', models.CharField(max_length=20, verbose_name='City')),
                ('ZipCode', models.CharField(max_length=10, verbose_name='Zip code')),
                ('State', models.CharField(max_length=10, verbose_name='State')),
                ('Country', models.CharField(max_length=20, verbose_name='Country')),
                ('Phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('LegalName', models.CharField(max_length=50, verbose_name='Legal Name')),
                ('Fax', models.CharField(max_length=50, verbose_name='Fax')),
                ('Email', models.CharField(max_length=50, verbose_name='Email')),
                ('DUNs', models.CharField(max_length=9, verbose_name='DUNs')),
                ('CAGE', models.CharField(max_length=50, verbose_name='CAGE')),
                ('POC', models.CharField(max_length=50, verbose_name='Point of Contact')),
                ('TIN', models.CharField(max_length=11, verbose_name='TIN')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Name')),
                ('Location', models.CharField(max_length=50, verbose_name='Location')),
                ('Fax', models.CharField(max_length=50, verbose_name='Fax')),
                ('Supervisor', models.CharField(max_length=50, verbose_name='Supervisor')),
                ('Phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('ContractID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Contract')),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Department_Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Contract')),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Customer')),
                ('DepartmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField(max_length=20, verbose_name='Resource Last Name')),
                ('MName', models.CharField(max_length=20, verbose_name='Resource First Name')),
                ('LName', models.CharField(max_length=20, verbose_name='Resource First Name')),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, verbose_name='Gender')),
                ('PersonalEmail', models.CharField(max_length=50, verbose_name='Personal Email')),
                ('PMIEmail', models.CharField(max_length=50, verbose_name='PMI Email')),
                ('TypeOfContract', models.CharField(max_length=20, verbose_name='Type of Contract')),
                ('Addresses', models.CharField(max_length=30, verbose_name='Addresses')),
                ('City', models.CharField(max_length=20, verbose_name='City')),
                ('ZipCode', models.CharField(max_length=10, verbose_name='Zip code')),
                ('State', models.CharField(max_length=10, verbose_name='State')),
                ('Country', models.CharField(max_length=20, verbose_name='Country')),
                ('Phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('BirthDate', models.DateField(default=datetime.date.today, verbose_name='Birth Date')),
                ('DateOfHire', models.DateField(default=datetime.date.today, verbose_name='Date of Hire')),
                ('PMICareerTitle', models.CharField(max_length=50, verbose_name='PMI Career Title    ')),
                ('ResourceType', models.CharField(max_length=20, verbose_name='Resource Type')),
                ('GSALaborCategory', models.CharField(max_length=20, verbose_name='GSA Labor Category')),
                ('VacationHour', models.CharField(max_length=20, verbose_name='Vacation Hour')),
                ('SickLeaveHour', models.CharField(max_length=20, verbose_name='Sick Leave Hour')),
                ('EmployementStatus', models.CharField(max_length=50, verbose_name='Employment Status')),
                ('ContractLaborCategory', models.CharField(max_length=20, verbose_name='Contract Labor Category')),
                ('RecruitmentSource', models.CharField(max_length=50, verbose_name='Recruitment Source')),
                ('ResponsibleRecruiter', models.CharField(max_length=50, verbose_name='Responsible Recruiter')),
                ('HUBzone', models.BooleanField(default=True, verbose_name='HUBzone')),
                ('ProbationaryEnd', models.DateField(default=datetime.date.today, verbose_name='Probationary End')),
                ('TerminationDate', models.DateField(default=datetime.date.today, verbose_name='Termination Date')),
                ('Department', models.CharField(max_length=50, verbose_name='Department')),
                ('WorkLocation', models.CharField(max_length=50, verbose_name='Work Location')),
                ('Billable', models.BooleanField(default=True, verbose_name='Billable')),
                ('SalaryType', models.CharField(max_length=20, verbose_name='Salary Type')),
                ('Salary', models.IntegerField(verbose_name='Salary')),
                ('ClearanceStatus', models.CharField(max_length=20, verbose_name='Clearance Status')),
                ('ClearedDate', models.DateField(default=datetime.date.today, verbose_name='Cleared Date')),
                ('ClearedType', models.CharField(max_length=20, verbose_name='Cleared Type')),
                ('Rehire', models.BooleanField(default=True, verbose_name='Rehire (T/F)')),
                ('_401KEligible', models.BooleanField(default=True, verbose_name='401K Eligible')),
                ('OrientationDate', models.DateField(default=datetime.date.today, verbose_name='Orientation Date')),
                ('ClientBillRate', models.CharField(max_length=20, verbose_name='Client Bill Rate')),
                ('GSA_vehicle', models.CharField(max_length=50, verbose_name='GSA Vehicle')),
                ('GSA_rate', models.CharField(max_length=50, verbose_name='GSA Rate')),
                ('CAMPINSent', models.CharField(max_length=50, verbose_name='CAMPINSent')),
                ('PaycomLogin', models.CharField(max_length=50, verbose_name='Paycom Login')),
                ('eFAACT', models.CharField(max_length=50, verbose_name='eFAACT')),
                ('Computer', models.CharField(max_length=50, verbose_name='Computer')),
                ('BusinessCard', models.CharField(max_length=50, verbose_name='Business Card')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Name')),
                ('Admin', models.CharField(max_length=50, verbose_name='Admin')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleGroup_Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Employee')),
                ('GoogleGroupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.GoogleGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=50, verbose_name='Address')),
                ('CAGE', models.CharField(max_length=50, verbose_name='CAGE')),
                ('City', models.CharField(max_length=20, verbose_name='City')),
                ('ZipCode', models.CharField(max_length=10, verbose_name='Zip code')),
                ('State', models.CharField(max_length=10, verbose_name='State')),
                ('Country', models.CharField(max_length=20, verbose_name='Country')),
                ('Phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('LegalName', models.CharField(max_length=50, verbose_name='Legal Name')),
                ('Fax', models.CharField(max_length=50, verbose_name='Fax')),
                ('Email', models.CharField(max_length=50, verbose_name='Email')),
                ('DBA', models.CharField(max_length=50, verbose_name='DBA')),
                ('DUNs', models.CharField(max_length=9, verbose_name='DUNs')),
                ('POC', models.CharField(max_length=50, verbose_name='Point of Contact')),
                ('TIN', models.CharField(max_length=11, verbose_name='TIN')),
                ('Type', models.CharField(max_length=20, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='POC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=50, verbose_name='Address')),
                ('Phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('Email', models.CharField(max_length=50, verbose_name='Email')),
                ('LName', models.CharField(max_length=20, verbose_name='Resource First Name')),
                ('FName', models.CharField(max_length=20, verbose_name='Resource Last Name')),
                ('ContractID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Contract')),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Customer')),
                ('PartnerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Partner')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Contract')),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZipCode', models.CharField(max_length=10, verbose_name='Zip code')),
                ('TIN', models.IntegerField(verbose_name='TIN')),
                ('State', models.CharField(max_length=10, verbose_name='State')),
                ('POC', models.CharField(max_length=50, verbose_name='Point of Contact')),
                ('Phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('LegalName', models.CharField(max_length=50, verbose_name='Legal Name')),
                ('Fax', models.CharField(max_length=50, verbose_name='Fax')),
                ('Email', models.CharField(max_length=50, verbose_name='Email')),
                ('DUNs', models.CharField(max_length=50, verbose_name='DUNs')),
                ('DBA', models.CharField(max_length=50, verbose_name='DBA')),
                ('Country', models.CharField(max_length=20, verbose_name='Country')),
                ('City', models.CharField(max_length=20, verbose_name='City')),
                ('CAGE', models.CharField(max_length=50, verbose_name='CAGE')),
                ('Address', models.CharField(max_length=50, verbose_name='Address')),
            ],
        ),
        migrations.AddField(
            model_name='vendor_contract',
            name='VendorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Vendors'),
        ),
        migrations.AddField(
            model_name='googlegroup_employee',
            name='VendorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Vendors'),
        ),
        migrations.AddField(
            model_name='employee',
            name='VendorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Vendors'),
        ),
        migrations.AddField(
            model_name='department_employee',
            name='EmployeeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Employee'),
        ),
        migrations.AddField(
            model_name='department_employee',
            name='VendorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Vendors'),
        ),
        migrations.AddField(
            model_name='customer_vendor',
            name='VendorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Vendors'),
        ),
        migrations.AddField(
            model_name='customer_partner',
            name='PartnerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Partner'),
        ),
        migrations.AddField(
            model_name='customer_employee',
            name='EmployeeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Employee'),
        ),
        migrations.AddField(
            model_name='customer_employee',
            name='VendorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Vendors'),
        ),
        migrations.AddField(
            model_name='contract_employee',
            name='CustomerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Customer'),
        ),
        migrations.AddField(
            model_name='contract_employee',
            name='EmployeeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Employee'),
        ),
        migrations.AddField(
            model_name='contract_employee',
            name='VendorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Vendors'),
        ),
        migrations.AddField(
            model_name='contract',
            name='CustomerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Customer'),
        ),
    ]
